changes for web-sdk sample fpe compatibility
AgoraIO-Community/app-builder-core pull request #174
Opened 2022-09-05 13:55 UTC by Adictya

ClickupTicket: [APP-3506](https://app.clickup.com/t/8556478/APP-3506)

2022-09-06 08:56 UTC, nitte93 requested changes

2022-09-06 08:56 UTC, nitte93 commented on template/src/pages/Create.tsx
> +        'DEBUG(aditya)-SDKEvents: joinMeetingWithPhrase event called', phrase
update this log

2022-09-08 10:12 UTC, Adictya commented on template/src/pages/Create.tsx
> +        'DEBUG(aditya)-SDKEvents: joinMeetingWithPhrase event called', phrase
Updated in latest commit

2022-09-09 10:35 UTC, nitte93 approved these changes
LGTM

2022-09-09 10:35 UTC, merged