Feature/raise hand
AgoraIO-Community/app-builder-core pull request #61
Opened 2022-01-04 05:09 UTC by SupriyaAdep

# Related Issue
- Mention your issue description here
- clickup ticket

# Propossed changes/Fix
- Change 1
- Change 2
- ...

# Additional Info 
- Any additional info or context for the reviewer

# Checklist
- [ ] Tested on local/dev branch for all major platforms (Android, IOS, Desktop, Web).
- [ ] No commented out code
- [ ] Is any third party library, service used
- [ ] Tests
- [ ] If this change requires updates outside of the code, like updates in core, react-ui-kit, RTM/RTC configure.

# Dependent PRs 
- Mention dependent PR links.

# Screenshots

Original                |          Updated
:---------------------:  | :-----------------------:
**original screenshot** |  **updated screenshot**

2022-01-19 08:32 UTC, nitte93 commented on template/bridge/rtc/webNg/RtcEngine.ts
> +export enum role {
```suggestion
export enum Role {
```

2022-01-19 08:34 UTC, nitte93 commented on template/bridge/rtc/webNg/RtcEngine.ts
> +      if (clientRole == ClientRole.Audience) {
What's the use of return, also use the defined Role enum
```suggestion
if (clientRole == ClientRole.Audience) {
        await this.client.setClientRole(Role.Audience, {level: 1});
      }
       if (clientRole == ClientRole.Broadcaster) {
        await this.client.setClientRole(Role.host);
        return;
      }
```

2022-01-19 08:38 UTC, technophilic commented
![image](https://user-images.githubusercontent.com/17137314/150093913-9a543cd1-4404-4728-aeb3-496e278e1144.png)

Alignment looks off in precall.
Also the text should read Joining Room - New
Is this change a part of this PR?

2022-01-19 10:13 UTC, nitte93 commented on template/src/components/ChatContext.ts
> +  raiseHandApprovedRequestRecall = 'RAISE_HAND_APPROVED_REQUEST_RECALL',
raiseHandApprovedRequestRecall , is this suppose to be here ?

2022-01-19 10:42 UTC, nitte93 commented on template/bridge/rtc/webNg/RtcEngine.ts
> +  // async setChannelProfile(profile: ChannelProfile): Promise<void> {
remove

2022-01-19 10:43 UTC, nitte93 commented on template/src/components/RTMConfigure.tsx
> +            // if (Object.values(controlMessageEnum).includes(msg)) break;
remove

2022-01-19 10:44 UTC, nitte93 commented on template/src/components/RTMConfigure.tsx
> +              // console.log(
remove console log and commented piece of code from everywhere

2022-01-19 10:49 UTC, nitte93 commented on template/src/components/livestream/LiveStreamContext.tsx
> +  const [currLiveStreamRequest, setLiveStreamRequest] = useState<Array<number>>(
Is there any benefit of using array over kev: value pair object

2022-01-20 06:50 UTC, SupriyaAdep commented on template/bridge/rtc/webNg/RtcEngine.ts
> +import isLiveStreamingEnabled from '../../../src/utils/isLiveStreamingEnabled';
This is low priority,

2022-03-26 20:05 UTC, technophilic requested changes

2022-03-28 07:02 UTC, SupriyaAdep commented on template/src/components/RTMConfigure.tsx
>    let engine = useRef<RtmEngine>(null!);
Blocker

2022-03-28 17:39 UTC, SupriyaAdep commented on template/bridge/rtc/webNg/RtcEngine.ts
> +  async setChannelProfile(profile: ChannelProfile): Promise<void> {
Added ternary operator.

2022-03-28 17:40 UTC, SupriyaAdep commented on template/bridge/rtc/webNg/RtcEngine.ts
> +        await this.client.setClientRole(role.audience, {level: 1});
options is passed as second argument, instead of hardcoding it as level1

2022-03-28 17:40 UTC, SupriyaAdep commented on template/bridge/rtm/web/index.ts
> +  addOrUpdateChannelAttributes(
yes

2022-03-28 17:41 UTC, SupriyaAdep commented on template/bridge/rtm/web/index.ts
> +  addListener<EventType extends keyof RtmClientEvents>(
new sdk updates has addListener.

2022-03-28 17:41 UTC, SupriyaAdep commented on template/src/components/Precall.tsx
> +  const [dim, setDim] = useState<Array<number>>([
add tuple

2022-03-28 17:41 UTC, SupriyaAdep commented on template/src/components/RTMConfigure.tsx
> +    window.addEventListener('beforeunload', handBrowserClose);
moved method inside useeffect

2022-03-28 17:44 UTC, SupriyaAdep commented on template/src/components/RTMConfigure.tsx
>    const [userList, setUserList] = useState<{[key: string]: any}>({});
Tracked this requirement in ticket. https://app.clickup.com/t/8556478/APP-1164. Will be completed with FPE release

2022-03-28 17:44 UTC, SupriyaAdep commented on template/src/subComponents/livestream/ApprovedLiveStreamControlsView.tsx
> +  p_styles: any;
Tracked this requirement in ticket. https://app.clickup.com/t/8556478/APP-1164. Will be completed with FPE release

2022-03-28 17:50 UTC, SupriyaAdep commented on template/src/components/livestream/LiveStreamContext.tsx
> +  const localMe = useRef({uid: localUid, status: ''});
Done.

2022-03-28 18:54 UTC, SupriyaAdep commented on template/src/components/livestream/LiveStreamContext.tsx
> +    const {stopUserScreenShare} = useContext(ScreenshareContext);
Added common screensharecontext. resolved

2022-03-28 19:01 UTC, SupriyaAdep commented on template/src/components/livestream/LiveStreamContext.tsx
> +export const LiveStreamContextProvider = (props: any) => {
Props interface is added, but one prop(setRtcProps) is still any .
Tracked as requirement in: https://app.clickup.com/t/8556478/APP-1164

2022-03-28 19:20 UTC, SupriyaAdep commented on package.json
> +    "uikit": "rm -rf template/agora-rn-uikit && git clone https://github.com/AgoraIO-Community/ReactNative-UIKit template/agora-rn-uikit && cd template/agora-rn-uikit && git checkout feature/ui-kit/r
reverted.

2022-03-29 06:06 UTC, merged