Install FPE and refactored Precall
AgoraIO-Community/app-builder-core pull request #86
Opened 2022-02-04 11:37 UTC by HariharanIT

# Related Issue
- Mention your issue description here
- clickup ticket - 
   https://app.clickup.com/t/8556478/APP-901 
   https://app.clickup.com/t/8556478/APP-902

# Propossed changes/Fix
- Change 1
- Change 2
- ...

# Additional Info 
- Any additional info or context for the reviewer

# Checklist
- [ ] Tested on local/dev branch for all major platforms (Android, IOS, Desktop, Web).
- [ ] No commented out code
- [ ] Is any third party library, service used
- [ ] Tests
- [ ] If this change requires updates outside of the code, like updates in core, react-ui-kit, RTM/RTC configure.

# Dependent PRs 
- Mention dependent PR links.

# Screenshots

Original                |          Updated
:---------------------:  | :-----------------------:
**original screenshot** |  **updated screenshot**

2022-02-14 11:36 UTC, technophilic commented
`test-fpe` should not be committed inside the core repository.

2022-02-14 14:01 UTC, technophilic requested changes

2022-02-18 05:17 UTC, HariharanIT commented on template/src/App.tsx
> +    installPlugin()
Now install method move to seperate file

2022-02-18 05:18 UTC, HariharanIT commented on template/src/pages/VideoCall/index.tsx
> +const VideoCallProvider = (props:any) => {
done

2022-02-18 05:18 UTC, HariharanIT commented on template/src/pages/VideoCall/index.tsx
> +const VideoCallContext = React.createContext((null as unknown) as VideoCallContextType);
done

2022-02-18 05:18 UTC, HariharanIT commented on template/src/pages/Authenticate.tsx
>    let onLayout = (e: any) => {
done

2022-02-18 05:18 UTC, HariharanIT commented on template/src/components/chat-ui/index.tsx
> +const ChatUIContext = createContext((null as unknown) as ChatUIInterface);
done

2022-02-18 05:19 UTC, HariharanIT commented on template/src/components/common/Error.tsx
> +const ErrorContext = React.createContext((null as unknown) as ErrorContextType);
done

2022-02-18 05:19 UTC, HariharanIT commented on template/src/components/dimension/DimensionContext.ts
> +const DimensionContext = createContext((null as unknown) as DimensionContextInterface);
done

2022-02-18 05:19 UTC, HariharanIT commented on template/src/components/precall/LocalMute.tsx
> +          {PreCallLocalVideoMute && <PreCallLocalVideoMute />}
done

2022-02-18 05:19 UTC, HariharanIT commented on template/src/components/precall/PreCall.tsx
> +const Precall = (props: any) => {
done

2022-02-18 05:19 UTC, HariharanIT commented on template/src/components/precall/PreCall.tsx
> +          {PreCallVideoPreview && <PreCallVideoPreview />}
done

2022-02-18 05:20 UTC, HariharanIT commented on template/src/components/precall/PreCallContext.ts
> +const PreCallContext = createContext((null as unknown) as PreCallContextInterface);
done

2022-02-18 05:20 UTC, HariharanIT commented on template/src/components/precall/PreCallProvider.tsx
> +const PreCallProvider = (props:any) => {
done

2022-02-18 05:20 UTC, HariharanIT commented on template/src/components/precall/index.tsx
> +const PreCallLocalAudioMute = () => <LocalAudioMute />;
done

2022-02-18 05:20 UTC, HariharanIT commented on template/src/components/precall/joinCallBtn.tsx
> +        disabled={!queryComplete || username.trim() === ''}
done

2022-02-18 05:20 UTC, HariharanIT commented on template/src/components/precall/setName.tsx
> +      {PreCallTextInput && <PreCallTextInput/>}
done

2022-02-18 05:20 UTC, HariharanIT commented on template/src/components/Controls.tsx
>  const Controls = (props: any) => {
done

2022-02-18 05:20 UTC, HariharanIT commented on template/src/utils/common.tsx
> +const isMobileWeb = () => {
done

2022-02-18 05:20 UTC, HariharanIT commented on template/src/pages/Create/ShareLink.tsx
> +const ShareLinkContext = React.createContext((null as unknown) as ShareLinkContextType);
done

2022-02-18 05:25 UTC, HariharanIT commented on template/src/subComponents/TextWithTooltip.tsx
> +export default isMobileWeb() ? TextWithToolTipNative : TextWithToolTip;
done

2022-02-18 05:26 UTC, HariharanIT commented on template/src/components/Controls.tsx
> +        {isMobileWeb() ? (
No difference. i think its now rename as mobileOrTablet for betting understanding

2022-02-18 05:27 UTC, HariharanIT commented on template/src/components/dimension/DimensionProvider.tsx
> +  const getDimensionData = (width?: number, height?: number):{dim:(number | boolean)[],isDesktop: boolean} => {
Typescript throwing error if i not specified the return type. that why i added it.

2022-02-18 05:27 UTC, HariharanIT commented on template/fpe-api/index.ts
> +let FpeApiConfig: FpeApiInterface = {
Now we are not mutating fpe object

2022-02-18 05:29 UTC, HariharanIT commented on template/fpe-api/index.ts
> +  installComponents(config?.components)
with current useFpe design. we are not needed pick method for now. if any need i will use this

2022-04-07 06:59 UTC, merged